Update python script for generating the M. genitalium networks
LLNL/wcs pull request #102
Opened 2021-04-20 20:36 UTC by Kgeorgouli

2021-04-20 21:00 UTC, JaeseungYeom requested changes
Some comments

2021-04-20 21:00 UTC, JaeseungYeom commented on scripts/mg_net/generate_network.py
> +          species_conc = model.getSpecies(name_species).getInitialAmount()*1000 / (6.02214e23*5.23e-16)
Is it possible to make a constant definition for 6.02214e23 and use the name instead of the value?
Also, use it in other places where the value is used.
I would suggest the same for 5.23e-16. However, what is this value?

2021-04-20 21:00 UTC, JaeseungYeom commented on scripts/mg_net/generate_network.py
> +                <cn type="e-notation"> 6.02214 <sep/> 23 </cn>
Will it somehow be possible to use the value of the constant defined for Avogardo number?

2021-04-20 21:00 UTC, JaeseungYeom commented on scripts/mg_net/generate_network.py
>          min_conc = 100000000000
How do we know if this value is large enough? If this value is compared against a floating point number, this should be expressed in floating point number as well.

2021-04-20 21:00 UTC, JaeseungYeom commented on scripts/mg_net/generate_network.py
> +        if (total < 7 ):
Can we make 7 as a parameter, for example with allowed values from 3 to 10 and 7 being the default?

2021-04-21 15:32 UTC, Kgeorgouli commented on scripts/mg_net/generate_network.py
> +          species_conc = model.getSpecies(name_species).getInitialAmount()*1000 / (6.02214e23*5.23e-16)
Done. I have replaced both numbers with constant definitions. The second number ( 5.23e-16)  is the volume of space.

2021-04-21 15:34 UTC, Kgeorgouli commented on scripts/mg_net/generate_network.py
>          min_conc = 100000000000
After the conversion, the calculated concentration are very small numbers. Therefore, I thinsk this is a large enough number. I have replaced the number as min_conc = 100000000000.00. I hope its is okay.

2021-04-21 16:05 UTC, Kgeorgouli commented on scripts/mg_net/generate_network.py
> +        if (total < 7 ):
Done. I have put this number as parameter (maximum sum stoichiometry as the threshold between the approach 1 and approach 3). However we have a problem here. The thing is that if we have a number 5 in this parameter then I take an  error. The problem is that we cover specific cases of reactions in specific cellular processes in approach 3 and if a value smaller is selected then we will have new reactions that we do not cover.  Do you think that we have to change the allowed values from 6 to 10?

2021-04-21 16:12 UTC, Kgeorgouli commented on scripts/mg_net/generate_network.py
> +                <cn type="e-notation"> 6.02214 <sep/> 23 </cn>
Unfortunately, I cannot do this because I have to define explicitly the exponent of this number.

2021-06-19 06:39 UTC, JaeseungYeom approved these changes

2021-06-29 22:25 UTC, merged