Generate c code and add testing SBML/antimony files
LLNL/wcs pull request #17
Opened 2020-07-20 21:48 UTC by Kgeorgouli

2020-07-21 04:38 UTC, JaeseungYeom commented
It could have been better if there were two separate PRs, one commit per PR. Forrtunately, commits are clearly distinctive. So, it is ok.
I think we do not need the model output files since those can be easily reproduced by running the code.

2020-07-22 08:25 UTC, JaeseungYeom requested changes
I sent you a file with all of my suggested updates applied.

2020-07-22 19:33 UTC, JaeseungYeom approved these changes
Just a couple of more changes.

2020-07-22 19:33 UTC, JaeseungYeom commented on src/utils/generate_C_code.cpp
> +      dependencies_no_dupl.insert(nit, *it);
replace nit with dependencies_no_dupl.begin()

2020-07-22 19:33 UTC, JaeseungYeom commented on src/utils/generate_C_code.cpp
> +#include "cstdio"
replace "cstdio" with \<cstdio\>

2020-07-22 19:33 UTC, JaeseungYeom commented on src/utils/generate_C_code.cpp
> +  std::vector<std::string>::const_iterator it, nit;
we do not need `nit` with the change applied to line 131.

2020-07-22 19:44 UTC, JaeseungYeom approved these changes
and some more

2020-07-22 19:44 UTC, JaeseungYeom commented on src/utils/generate_C_code.cpp
> +    std::cout <<") {\n";
space after `<<`

2020-07-22 19:44 UTC, JaeseungYeom commented on src/utils/generate_C_code.cpp
> +    std::cout <<"\n}\n\n";
space after `<<`

2020-07-22 19:44 UTC, JaeseungYeom commented on src/utils/generate_C_code.cpp
> +        std::cout <<", ";
space after `<<`

2020-07-22 19:44 UTC, JaeseungYeom commented on src/utils/generate_C_code.cpp
> +      if (ia!=num_arg-1) {
space around `!=`

2020-07-22 19:44 UTC, JaeseungYeom commented on src/utils/generate_C_code.cpp
> +      std::cout << "static constexpr Real _init_" << species.getIdAttribute() << " = 0;\n";
break this long line into two

2020-07-23 12:43 UTC, JaeseungYeom commented
Maybe the file name should be `generate_cxx_code.cpp` because it generate c++ code.

2020-07-23 13:02 UTC, JaeseungYeom commented
To fix the conflict in CMakeList.txt, change WCS_UTILS_TARGETS to WCS_EXEC_TARGETS

2020-07-23 16:17 UTC, Kgeorgouli commented
I have done all the changes as you requested.

2020-07-23 17:56 UTC, JaeseungYeom commented
Resolve the conflict and then merge it. Thanks a lot!

2020-07-23 18:08 UTC, Kgeorgouli commented
I made the rebase and fixed the conflict as you suggested.

2020-07-23 18:09 UTC, JaeseungYeom commented on CMakeLists.txt
> +>>>>>>> Generate C code from a SBML file
remove these lines.

2020-07-23 18:10 UTC, JaeseungYeom commented on CMakeLists.txt
> +>>>>>>> Generate C code from a SBML file
> I made the rebase and fixed the conflict as you suggested.

That is great. Can you do once more by removing the lines shown above?

2020-07-23 18:16 UTC, Kgeorgouli commented
Done!

2020-07-23 18:24 UTC, JaeseungYeom commented
You can merge it now. If you still want to perfect it further, there are some invisible tabs '\t', which you can remove or replace with space.

2020-07-23 19:53 UTC, Kgeorgouli commented
I removed  also the invisible tabs but when I try to run the cmake, I take the following error "CMake Error: install(EXPORT "WCSTargets" ...) includes target "reaction-bin" more than once in the export set.
CMake Error in CMakeLists.txt:
  given target "reaction-bin" more than once."

2020-07-23 20:20 UTC, JaeseungYeom commented on CMakeLists.txt
> +>>>>>>> Generate C code from a SBML file
In the new file, it is around lines 463-471. Those need to be removed.

2020-07-23 20:21 UTC, JaeseungYeom commented
> I removed also the invisible tabs but when I try to run the cmake, I take the following error "CMake Error: install(EXPORT "WCSTargets" ...) includes target "reaction-bin" more than once in the export set.
> CMake Error in CMakeLists.txt:
> given target "reaction-bin" more than once."

The install block for `reaction-bin ssa-bin` need to be removed.

2020-07-23 20:51 UTC, Kgeorgouli commented
I have removed the install block for  reaction-bin ssa-bin  you requested and everything is okay now.

2020-07-23 21:00 UTC, JaeseungYeom commented
> I have removed the install block for reaction-bin ssa-bin as you requested and everything is okay now.

Excellent. Hit the green button!

2020-07-23 21:02 UTC, merged

2020-07-23 21:10 UTC, Kgeorgouli commented
> > I have removed the install block for reaction-bin ssa-bin as you requested and everything is okay now.
> 
> Excellent. Hit the green button!

Thank you very much for your help!